"""update percentage

Revision ID: 25ef94642611
Revises: 9c8b130360ec
Create Date: 2024-11-16 16:39:24.846556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ef94642611'
down_revision = '9c8b130360ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cashback_percentage', sa.Float(), nullable=True))
    op.drop_column('users', 'cashback_percentage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cashback_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('users', 'cashback_percentage')
    # ### end Alembic commands ###
