"""update percentage again

Revision ID: 484c53ddb12f
Revises: 25ef94642611
Create Date: 2024-11-16 16:54:18.640498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484c53ddb12f'
down_revision = '25ef94642611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cashback_percentage', sa.Float(), nullable=True))
    op.drop_column('users', 'cashback_percentge')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cashback_percentge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('users', 'cashback_percentage')
    # ### end Alembic commands ###
