services:
  postgres:
    image: postgres:latest
    container_name: prog-lr9
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bonus_program_db
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
